// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package model

import (
	"database/sql"
)

type Product struct {
	ID            int64          `json:"id"`
	Name          sql.NullString `json:"name"`
	Description   sql.NullString `json:"description"`
	ProductStatus sql.NullString `json:"product_status"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	ReservedAt    sql.NullInt64  `json:"reserved_at"`
}
